### ISSUE TITLE
It not works for me.

### ISSUE THREAD

**Issue by ghost** [flyzsd/mjpeg#1]
When I run this it not show web cam . 
The browser contineously loading the address `localhost:80` for long time.

**Comment by flyzsd** [comment]
can you please share the server logs? Make sure you have USB camera connected.. and this only works on windows platform

**Comment by ghost** [comment]
`"C:\Program Files\Java\jdk1.8.0_241\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\lib\idea_rt.jar=53213:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\bin" -Dfile.encoding=UTF-8 -classpath "D:\Github\mjpeg\bin;C:\Program Files\Java\jdk1.8.0_241\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_241\jre\lib\rt.jar;D:\Github\mjpeg\lib\lti-civil.jar;D:\Github\mjpeg\lib\logback-classic-1.0.6.jar;D:\Github\mjpeg\lib\logback-core-1.0.6.jar;D:\Github\mjpeg\lib\slf4j-api-1.7.7.jar" sandbox.java.camera.mjpeg.Main
10:49:40.614 [main] DEBUG sandbox.java.camera.mjpeg.Main - Uncaught throwable in getBestCaptureStream()
com.lti.civil.CaptureException: java.lang.UnsatisfiedLinkError: D:\Github\mjpeg\civil.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
	at com.lti.civil.impl.jni.NativeCaptureSystemFactory.createCaptureSystem(NativeCaptureSystemFactory.java:24) ~[lti-civil.jar:na]
	at sandbox.java.camera.mjpeg.Main.main(Main.java:64) ~[bin/:na]
Caused by: java.lang.UnsatisfiedLinkError: D:\Github\mjpeg\civil.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.8.0_241]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934) ~[na:1.8.0_241]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850) ~[na:1.8.0_241]
	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[na:1.8.0_241]
	at java.lang.System.loadLibrary(System.java:1122) ~[na:1.8.0_241]
	at com.lti.civil.impl.jni.NativeCaptureSystemFactory.createCaptureSystem(NativeCaptureSystemFactory.java:21) ~[lti-civil.jar:na]
	... 1 common frames omitted
10:49:40.622 [main] INFO  sandbox.java.camera.mjpeg.Main - Server started, listening at port 8080
10:49:47.013 [main] INFO  sandbox.java.camera.mjpeg.Main - Client /127.0.0.1:53221 connected`

**Comment by ghost** [comment]
I am using windows 10.

**Comment by ghost** [comment]
help me !!!

**Comment by flyzsd** [comment]
as the stack trace clearly points out, it fails to load the 32 bit dll on 64 bit JVM.
two choice for you:

- Compile the dll into 64 bit (maybe more challenging for you)
- Use 32 bit JVM

**Comment by ghost** [comment]
Can you explain in detail?

**Comment by flyzsd** [comment]
this project is using this library [https://sourceforge.net/p/lti-civil/wiki/Home/](**lti-civil)** to communicate to USB camera.. At lower level, Java code is loading DLL via JNI to invoke OS specific APIs.

**Comment by flyzsd** [comment]
> this project is using this library [lti-civil](https://sourceforge.net/p/lti-civil/wiki/Home/) to communicate to USB camera.. At lower level, Java code is loading DLL via JNI to invoke OS specific APIs.

**Comment by flyzsd** [comment]
this lit-civil library is no longer properly maintained.. you better seek alternative solutions to use camera in JVM

**Comment by ghost** [comment]
I want to stream the PC screen over http.

Like this https://github.com/jcodec/jcodec/issues/155 .

Can I done this with your project?

help me to do this!!!

**Comment by flyzsd** [comment]
I am afraid this project will not fit your purpose...

**Comment by ghost** [comment]
Can you guide me to achieve this https://github.com/flyzsd/mjpeg/issues/1#issuecomment-635179625 ?

Because , I am new to java web app.

**Comment by flyzsd** [comment]
it is easier that you download 32 bit JRE to run this program
https://www.oracle.com/java/technologies/javase-jre8-downloads.html
